### ISSUE TITLE
Fails to seal passphrase with tpm2-abrmd enabled

### ISSUE THREAD

**Issue by WenzongFan** [jiazhang0/cryptfs-tpm2#1]
I got an issue like this:

$ export TPM2TOOLS_TCTI_NAME=tabrmd
$ export TSS2_TCTI=tabrmd
$ cryptfs-tpm2 -q seal all -P auto

**(process:xx): WARNING **: read on fd 7 produced error: 14, Bad address
[ERROR]: Unable to get the TPM PCR banks (0xa0001)
[ERROR]: Unsupported PCR bank algorithm

**Comment by liuqun** [comment]
检查一下后台进程 tpm2-abrmd 是不是已经正常启动了?
```
ps -aux |grep tpm2-abrmd
```

**Comment by WenzongFan** [comment]
I believe the tpm2-abrmd is in running while the error occurs, and the error is from an older version of cryptfs-tpm2. After I updated the cryptfs-tpm2 and tpm2*, I got a new error about:

read on istream 0x... produced error: Too large count value passed to g_input_stream_read

There's a workaround is unset the TSS2_TCTI from env.

**Comment by jiazhang0** [comment]
I definitely miss this for a while :(

In the newer tpm2-tools, the valid name for tcti interface tabrmd should be

```
struct {
    char       *name;
    tcti_init   init;
} tcti_map_table[] = {
#ifdef HAVE_TCTI_DEV
    ADD_TCTI("device", tpm2_tools_tcti_device_init),
#endif
#ifdef HAVE_TCTI_SOCK
    ADD_TCTI("socket", tpm2_tools_tcti_socket_init),
#endif
#ifdef HAVE_TCTI_TABRMD
    ADD_TCTI("abrmd", tpm2_tools_tcti_abrmd_init)
#endif
};
```

Obviously "tabrmd" for TPM2TOOLS_TCTI_NAME is invalid already. The latest cryptfs-tpm2 has changed to use "abrmd". Additionally, TSS2_TCTI created by cryptfs-tpm2 still use "tabrmd".

So this is a mess totally. Each tss2 component almost implements a private env variable with different naming scheme for the tcti itnerface abrmd.

Note: cryptfs-tpm2 now is hosted on github.com/jiazhang0/cryptfs-tpm2.git not github.com/WindRiver-OpenSourceLabs/cryptfs-tpm2.git.

**Comment by jiazhang0** [comment]
Note that the name change occurs since tpm2-tools 3.0.
