### ISSUE TITLE
cryptfs-tpm2 on kernel 4.9

### ISSUE THREAD

**Issue by LinhDNguyen** [jiazhang0/cryptfs-tpm2#10]
Hi. I'm so interested in your project and want to use on my board. But unfortunately, the latest kernel on my board is 4.9, while the tmprm driver is only available since kernel 4.12.
Do you have any idea that I can use cryptfs-tpm2 on this old kernel? Thank you.

**Comment by jiazhang0** [comment]
Not sure whether this issue still exists. Closed.
