### ISSUE TITLE
Compile error at the latest one

### ISSUE THREAD

**Issue by SeiUnMito** [jiazhang0/cryptfs-tpm2#14]
Failed to build latest.

capability.c: In function ‘capability_read_public’:
capability.c:53:9: error: ‘TPM2_PT_TPM2_HR_PERSISTENT’ undeclared (first use in this function); did you mean ‘TPM2_PT_HR_PERSISTENT’?
   53 |         TPM2_PT_TPM2_HR_PERSISTENT, &more_data,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         TPM2_PT_HR_PERSISTENT
capability.c:53:9: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [<builtin>: capability.o] Error 1
make[2]: Leaving directory '/home/linux/cryptfs-tpm2/src/lib'
make[1]: *** [Makefile:9: install] Error 2
make[1]: Leaving directory '/home/linux/cryptfs-tpm2/src'
make: *** [Makefile:12: install] Error 2

**Comment by jiazhang0** [comment]
Fixed by https://github.com/jiazhang0/cryptfs-tpm2/commit/684b868e68afef9bcbfecd20ea4da2f220445d03
