### ISSUE TITLE
Faild to build with latest meta-secure-core

### ISSUE THREAD

**Issue by yizhao1** [jiazhang0/cryptfs-tpm2#2]
The meta-secure-core commit dc173c7a8dff4ac28ea0b075baa664aee5b92e6b updated tpm2 related packages from 1.x to 2.x which makes the cryptfs-tpm2 build failed:

In file included from init.c:34:
/buildarea/build/tmp/work/i586-poky-linux/cryptfs-tpm2/0.6.3+gitAUTOINC+fb49abad57-r0/git/src/include/cryptfs_tpm2.h:64:10: fatal error: tcti/tcti_socket.h: No such file or directory
 #include <tcti/tcti_socket.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'init.o' failed
make[2]: *** [init.o] Error 1

**Comment by jiazhang0** [comment]
@yizhao1 I believe this PR https://github.com/jiazhang0/cryptfs-tpm2/pull/4 is resolving this issue.

**Comment by jiazhang0** [comment]
The newest commit https://github.com/jiazhang0/cryptfs-tpm2/commit/cb83b1d02e163d2e343e9e0bc3565c1d2c601b84 has fixed this issue.
