### ISSUE TITLE
Issues for luks-setup

### ISSUE THREAD

**Issue by yizhao1** [jiazhang0/cryptfs-tpm2#20]
Hi Jia,

I have tested latest luks-setup with tpm2 support and found some issues:

1. enroll_token doesn't work

I got the following error when running "luks-setup -V -f -e -d /dev/sdb1 -n luks_sdb1"
[?] Enrolling a new token for the unsealed passphrase ...
Device /dev/sdb1 is not a valid LUKS2 device.
[!] Failed to enroll a new token for the unsealed passphrase
[!] Unable to enroll a new token on the creation for the LUKS volume "luks_sdb1" ...

The root cause is "cryptsetup token import" only supports LUKS2, while the luks type is set to LUKS1 by default in create_luks_volume():
  local cmd="cryptsetup --type luks --cipher aes-xts-plain64 --hash sha256 \
        --use-random --key-file "$PASSPHRASE" luksFormat "$luks_dev"

So it's better to add an option to specify LUSK1/LUKS2.

2. enroll_recovery doesn't work

When I changed luks type to LUKS2 manually, I got another issue on enroll_recovery():
[?] Enrolling a new token for the unsealed passphrase ...
[!] Enrolled the new token for the unsealed passphrase
[!] Created the LUKS volume "luks_sdb1" on the backing device "/dev/sdb1"
[?] Enrolling keyslot and token for recovery ...
[?] Enrolling a new keyslot ...
[?] Retrieving the passphrase ...
[!] Unrecongnized token type "luks-setup-prompt-recovery"
[?] Enrolling a new token for the prompted passphrase for recovery ...
Failed to import token from file.
[!] Failed to enroll a new token for the prompted passphrase for recovery
[!] Unable to enroll a new token for recovery

This is because the token type is set to "luks-setup-prompt-recovery" and it isn't handled in retrieve_passphrase().

3. Run "luks-setup" without arguments should print usage, but now it doesn't:
$ luks-setup 
/usr/sbin/luks-setup: line 605: yum: command not found
[!] Failed to install the package "procps-ng"

Thanks,
Yi

**Comment by yizhao1** [comment]
4.The  "--no-tpm" option doesn't work

root@genericx86-64:~# luks-setup -V -f -t -d /dev/sdb1 -n luks_sdb1
Skip the detection of TPM 2.0 device
Prepare to prompt for the passphrase
Temporary directory created at "/tmp/luks-setup.p0jXa9"
The backing device "/dev/sdb1" is not a LUKS volume
[?] Creating the LUKS volume "luks_sdb1" ...
[?] Retrieving the passphrase ...
[!] Unrecongnized token type "luks-setup-prompt"
[?] Mapping the LUKS volume "luks_sdb1" with the token "luks-setup-prompt" ...
[?] Retrieving the passphrase ...
[!] Unrecongnized token type "luks-setup-prompt"
The LUKS volume "luks_sdb1" backing on /dev/sdb1 is created
[?] Cleaning up ...
[!] Exiting

**Comment by jiazhang0** [comment]
@yizhao1 Thanks for report these issues. All issues except the first one are fixed.

Currently there is no plan to support LUKS version 1, so instead of supporting it, luks-setup will check the default created LUKS version before token enrollment to avoid a token enrollment failure.
