### ISSUE TITLE
Upgrading libblkid1 from 2.30.2 to 2.31.1 causes cryptfs-tpm2 to error with "Too large count value passed to g_input_stream_read"

### ISSUE THREAD

**Issue by gblewis1** [jiazhang0/cryptfs-tpm2#3]
# Setup

* Ubuntu 18.04 running in Vagrant
* tpm2-abrmd version 1.3.1 (built and installed from source) 
* IBM tpm2 simulator 0.974 (built and installed from source)
* tpm2-tss version 1.4.0 (built and installed from source)
* tpm2-tools version 3.0.4 (built and installed from source)
* cryptfs-tpm2 version 0.6.3 (built and installed from source)
* tpm2-abrmd is being started with option --tcti=socket so it can talk to the IBM tpm2 simulator

# Command

sudo cryptfs-tpm2 --owner-auth blank unseal passphrase -P auto -o /tmp/passphrase

# Results

Result with libblkid 2.30.2-0.1ubuntu3 package installed: Pass phrase successfully unsealed.
Result with libblkid 2.31.1-0.4ubuntu1 package installed: 

Thu Aug 23 18:23:30 UTC 2018: [INFO] Use tabrmd as the default tcti interface

** (process:12769): WARNING **: read on istream 0x7f9980006b30 produced error: Too large count value passed to g_input_stream_read
Thu Aug 23 18:23:30 UTC 2018: [ERROR] Unable to get the TPM PCR banks (0xa0001)Thu Aug 23 18:23:30 UTC 2018: [ERROR] Unsupported PCR bank algorithm

# Observations

* tpm2_abrmd appears to depend on libblkid1 but not cryptfs-tpm2
* strace on tpm2_abrmd shows an unexpected client disconnect after cryptfs-tpm2 error message

**Comment by gblewis1** [comment]
tpm2-abrmd service file -- 

~~~~
[Unit]
Description=TPM2 Access Broker and Resource Management Daemon

[Service]
Type=dbus
Restart=always
RestartSec=5
EnvironmentFile=-/usr/etc/default/tpm2-abrmd
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
StandardError=syslog
ExecStart=/usr/sbin/tpm2-abrmd --tcti=socket
User=tss

[Install]
WantedBy=multi-user.target
~~~~

**Comment by gblewis1** [comment]
Strangely enough, it is not necessary to restart the tpm2-abrmd service after installing a "good" or "bad" libblkid1 package, to see the change in behavior in cryptfs-tpm2.

**Comment by gblewis1** [comment]
I did a git bisect with the upstream util-linux package and got this as the commit that introduces the error: https://github.com/karelzak/util-linux/commit/d2b0c6587d729a8e838821cb70d4de18c6969868

**Comment by gblewis1** [comment]
We appear to have found a solution here: https://github.com/tpm2-software/tpm2-abrmd/issues/514

**Comment by jiazhang0** [comment]
@gblewis1 I'm sorry I missed this. Thanks for your debugging. I will sync up with the latest in meta-secure-core.

**Comment by jiazhang0** [comment]
Too long to reproduce this issue. Closed.

**Comment by jiazhang0** [comment]
Too long to reproduce this issue. Closed.
