### ISSUE TITLE
Failed to build with latest commit

### ISSUE THREAD

**Issue by yizhao1** [jiazhang0/cryptfs-tpm2#9]
I got a build error when using the latest commit:

capability.c: In function 'capability_read_public':
capability.c:53:9: error: 'TPM2_PT_HR_PERSISTENT' undeclared (first use in this function); did you mean 'TPM2_HR_PERSISTENT'?
   53 |         TPM2_PT_HR_PERSISTENT, &more_data,
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         TPM2_HR_PERSISTENT
capability.c:53:9: note: each undeclared identifier is reported only once for each function it appears in
<builtin>: recipe for target 'capability.o' failed
make[2]: *** [capability.o] Error 1

Seems it related with commit 888c46c8279a390f2fca7284443ce5fbe35d18db

**Comment by jiazhang0** [comment]
Fixed by https://github.com/jiazhang0/cryptfs-tpm2/commit/684b868e68afef9bcbfecd20ea4da2f220445d03
